# Generated by Django 2.1.2 on 2019-02-22 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyDomainChecks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_dt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Domains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_dt', models.DateTimeField(auto_now_add=True)),
                ('url_core', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='dailydomainchecks',
            name='url_core',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whoismrsaemir.Domains'),
        ),
    ]
