# Generated by Django 2.1.2 on 2019-02-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whoismrsaemir', '0002_auto_20190222_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='domains',
            name='last_check',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
