# Generated by Django 2.1.2 on 2019-02-22 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whoismrsaemir', '0003_domains_last_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailydomainchecks',
            name='url_core',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='whoismrsaemir.Domains'),
        ),
    ]
