# Generated by Django 2.1.2 on 2019-02-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whoismrsaemir', '0004_auto_20190222_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domains',
            name='last_check',
            field=models.DateField(auto_now=True),
        ),
    ]
