# Generated by Django 2.1.2 on 2019-02-24 12:57

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('whoismrsaemir', '0005_auto_20190224_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='domains',
            name='count_down_status',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
