# Generated by Django 2.1.2 on 2019-03-11 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whoismrsaemir', '0008_domains_next_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whoisqueue',
            name='id',
            field=models.BooleanField(default=True, primary_key=True, serialize=False),
        ),
    ]
