# Generated by Django 2.1.2 on 2019-03-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whoismrsaemir', '0010_auto_20190311_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whoisqueue',
            name='id',
        ),
        migrations.AddField(
            model_name='whoisqueue',
            name='added',
            field=models.DateTimeField(auto_now=True, primary_key=True, serialize=False),
        ),
    ]
